app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

/*START: Comming soon login*/
/*Route::get('/',function(){
    return View::make('comming-soon');
});

Route::post('/',function(){
    $logincreds = array(
			'email'=>Input::get('em'),
			'password'=>Input::get('pwd'),
			'usertype'=>'admin'
		);

	$url = URL::to('admin');

	if( Auth::attempt( $logincreds ) )
		return Redirect::to($url);

    Session::flash('msg','<p style="color: white; text-align: center;">Account does not exist!</p>');
	return Redirect::to('/');
});*/
/*END: Comming soon login*/

Route::get('fudge', 'FacebookController@fbcheck');

Route::get('fblogin', 'FacebookController@fbregistration');

Route::get('/', 'HomeController@index');
Route::post('add-newsletter','HomeController@addEmailNewsletter');

Route::get('how-it-works',function(){
	$content = Page::find(1);

	return View::make('howworks')
			->with('ptitle','How It Works')
			->with('content',$content->content);
});

Route::group(array('prefix'=>'shop'), function(){
	Route::get('/', 'ShopController@index');

	Route::get('{id}', 'ShopController@product_datails');
	Route::post('addreview','ShopController@addRate');
});
Route::controller('gift-certificates','GiftcertController');

Route::get('shop_create_query', 'ShopController@create_query');
Route::get('shop_update_query', 'ShopController@update_query');

Route::controller('the-registry','RegcontributeController');
Route::get('registry','RegistryController@index');
Route::group(array('prefix'=>'registry','before'=>'auth'), function(){
	Route::get('create-registry-personal', 'RegistryController@create_personal');
	Route::post('createrpersonal', 'RegistryController@createpersonal');

	Route::get('create-registry-marriage', 'RegistryController@create_marriage');
	Route::post('createmarriage', 'RegistryController@createmarriage');

	Route::get('create-registry-others', 'RegistryController@create_others');
	Route::post('createothers', 'RegistryController@createothers');

	Route::get('setup', 'RegistryController@setupReg');
	Route::get('add-gift', 'RegistryController@addGift');
	Route::get('add-gift/{id}', 'ShopController@product_datails');
	Route::post('updateregistry', 'RegistryController@updateReg');
	Route::controller('wishing-well','WishingwellController');

	Route::get('additem','RegistryController@addItemReg');
	Route::post('addmanyproducts','RegistryController@addItemRegPost');
	Route::get('removeitem','RegistryController@removeprodreg');

	Route::post('check-code', 'RegistryController@checkcode');
	Route::get('the-registry', 'RegistryController@theregistry');

	Route::controller('contributors','ContributorsController');
});

Route::controller('contact-us','ContactController');

Route::controller('signup','SignupController');
Route::controller('login','LoginController');

Route::when('cart/*', 'auth');
Route::controller('cart','CartController');

/*My Account*/

Route::group(array('prefix'=>'my-account','before'=>'auth'), function(){
	Route::get('/', 'MyaccountController@index');
	Route::post('/', 'MyaccountController@update_personinfo');

	Route::get('payment-information', 'MyaccountController@paymentinfo');
	Route::post('payment-information', 'MyaccountController@update_paymentinfo');

	Route::get('order-history', 'MyaccountController@orderhistory');
	Route::get('order-detail/{id}', 'MyaccountController@orderdetail');

	Route::get('registry', 'MyaccountController@registry');
	Route::get('registry/{id}', 'MyaccountController@registrydetail');
	Route::get('registry-gotosetup', 'MyaccountController@gotosetup');
	
	Route::get('giftcerts', 'MyaccountController@giftcerts');

	Route::get('bye', 'MyaccountController@bye');
});

/*end:My Account*/

/*Footer Link*/
Route::get('about-us',function(){
	$content = Page::find(2);

	return View::make('about')
			->with('ptitle','About Us')
			->with('content',$content->content);
});

Route::get('help','HelpController@index');

Route::get('founder',function(){
	return View::make('founder')
			->with('ptitle','Founder');
});

Route::get('privacy-policy', function(){
	$content = Page::find(3);

	return View::make('privacy')
			->with('ptitle','Privacy Policy')
			->with('content',$content->content);
});

Route::get('terms-and-conditions', function(){
	$content = Page::find(4);

	return View::make('terms')
			->with('ptitle','Terms and Conditions')
			->with('content',$content->content);
});

Route::get('suppliers', function(){
	$content = Page::find(5);

	return View::make('suppliers')
			->with('ptitle','Suppliers')
			->with('content',$content->content);
});

Route::resource('blog','BlogController');
/*end:Footer Link*/

/*ADMIN PORTAL*/
Route::get('admin/login', 'AdminController@login');
Route::post('admin/gologin','AdminController@goLogin');
Route::post('admin/forgpass', 'AdminController@forgpass');
Route::group(array('prefix'=>'admin','before'=>'admin-auth'), function(){

	Route::get('/','AdminController@index');
	Route::get('bye-now', 'AdminController@adminlogout');

	Route::controller('users','AdminUserController');

	/*NOTES function*/
	Route::post('addnote', 'AdminController@addNote');
	Route::get('deletenote', 'AdminController@deleteNote');
	Route::get('changenotest', 'AdminController@changestNote');

	/*MESSAGE function*/
	Route::get('chat-room', 'AdminMessage@chatroom');

	/*CMS*/
	Route::controller('cms','AdminCMS');

	/*PRODUCTS*/
	Route::post('products/delete-multiple', 'AdminProductsController@destroy_multiple');
	Route::resource('products', 'AdminProductsController');
	Route::controller('gift-certs', 'AdminGcController');
	Route::controller('recipient', 'AdminRecipientController');

	/*Occassion*/
	Route::controller('occasions','AdminOccasionController');

	/*Blog*/
	Route::controller('blog','AdminBlogController');

	/*Registry*/
	Route::controller('registry','AdminRegistryController');

	/*Orders*/
	Route::controller('orders','AdminOrdersController');	

	/*Extra*/
	Route::controller('extra','AdminExtraController');

});
/*end:ADMIN PORTAL*/

app/models/Product.php
<?php

class Product extends Eloquent {

	protected $fillable = array('short_description','product_details','tags','validity','free_exchange','delivery_date','delivery_cost');

	public static function get_primary($id,$pre = "thumbnail")
	{
		$img = $pre.'_default.jpg';

		$g_img = DB::table('product-images')->where('product_id','=',$id)->where('primary','=',1)->pluck('image');

		if($g_img != '')
			$img = $pre.'_'.$g_img;

		return URL::to('uploads/products/'.$img);
	}

	public static function get_location($id)
	{
		$location = '';

		$g_location = DB::table('location-product')->where('product_id','=',$id)->orderBy('location')->get();
		$num_location = count($g_location);
		if($num_location > 0)
		{
			$ctr = 0;
			foreach ($g_location as $row)
			{
				$ctr++;

				$location .= $row->location;
				$location .= $num_location > $ctr ? ' / ':'';
			}
		}

		return $location;
	}

	public static function get_recipient($id)
	{
		$recipient = '';

		$g_recipient = DB::table('recipient-product')->where('product_id','=',$id)->get();
		$num_recipient = count($g_recipient);
		if($num_recipient > 0)
		{
			$ctr = 0;
			foreach ($g_recipient as $row)
			{
				$ctr++;

				$rec = explode(' ', DB::table('recipient')->where('recipient_id','=',$row->recipient_id)->pluck('recipient'));

				$recipient .= $rec[1];
				$recipient .= $num_recipient > $ctr ? ' / ':'';
			}
		}

		return $recipient;
	}

	public static function validate_products($input)
	{
		$rules = array(
				'product_name'=>'required',
				'short_description'=>'required',
				'product_details'=>'required',
				'price'=>'required',
				'delivery_date'=>'required',
				'delivery_cost'=>'required',
				'categories'=>'required'
			);

		$messages = array(
				'product_name.required'=>'Product Name is required',
				'short_description.required'=>'Short Description is required',
				'product_details.required'=>'Product Details is required',
				'price.required'=>'Price is required',
				'delivery_date.required'=>'Delivery Date is required',
				'delivery_cost.required'=>'Delivery Cost is required',
				'categories.required'=>'Please choose at least one(1) category'
			);

		return Validator::make( $input , $rules, $messages);
	}

	public static function search_product($filter)
	{
		if(count($filter) > 0)
		{
			$listfilter = array();

			$where = ' where '; $order = ' order by p.product_name ';
			$ctr = 0;
			
			if(array_key_exists('location', $filter))
			{
				$where .= " ( ";
				$loc = $filter['location'];

				foreach ($loc as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					$where .= " p.id in(select product_id from `location-product` where location = '{$value}') ";
					$ctr = 1;

					$listfilter[] = $value.'|location|'.$value;
				}

				$where .= " ) ";
			}

			if(array_key_exists('recipient', $filter))
			{
				$where .= $ctr == 1 ? " and ":"";

				$where .= " ( ";
				$recipient = $filter['recipient'];
				$ctr = 0;

				foreach ($recipient as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					$where .= " p.id in(select product_id from `recipient-product` where recipient_id = '{$value}') ";
					$ctr = 1;

					$listfilter[] = DB::table('recipient')->where('recipient_id','=',$value)->pluck('recipient').'|recipient|'.$value;
				}

				$where .= " ) ";
			}

			if(array_key_exists('pricer', $filter))
			{
				$where .= $ctr == 1 ? " and ":"";

				$where .= " ( ";
				$pricer = $filter['pricer'];
				$ctr = 0;

				foreach ($pricer as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					if($value == '501')
					{
						$v = floatval($value);
						$where .= " p.price >= {$v} ";
						$listfilter[] = '$'.$value.'|pricer|'.$value;
					}
					else
					{
						$v = explode('-', $value);
						$num1 = floatval($v[0]);
						$num2 = floatval($v[1]);
						$where .= " p.price between {$num1} and {$num2} ";
						$listfilter[] = '$'.$num1.'-$'.$num2.'|pricer|'.$value;
					}
					$ctr = 1;
				}

				$where .= " ) ";
			}

			if(array_key_exists('occasion', $filter))
			{
				$where .= $ctr == 1 ? " and ":"";

				$where .= " ( ";
				$occasion = $filter['occasion'];
				$ctr = 0;

				foreach ($occasion as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					$where .= " p.id in(select product_id from `product-occasion` where occ_id = '{$value}') ";
					$ctr = 1;

					$listfilter[] = DB::table('occasions')->where('id','=',$value)->pluck('occasion_name').'|occasion|'.$value;
				}

				$where .= " ) ";
			}

			if(array_key_exists('occasion-main', $filter))
			{
				$where .= $ctr == 1 ? " and ":"";

				$where .= " ( ";
				$occasion = $filter['occasion-main'];
				$ctr = 0;

				foreach ($occasion as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					$where .= " p.id in(select product_id from `product-occasion` po inner join occasions o on po.occ_id = o.id where occasion_type = '{$value}') ";
					$ctr = 1;

					$listfilter[] = DB::table('occasion-types')->where('id','=',$value)->pluck('occasion_type').'|occasion-main|'.$value;
				}

				$where .= " ) ";
			}

			if(array_key_exists('st', $filter))
			{
				$where .= $ctr == 1 ? " and ":"";

				$where .= " ( ";
				$st = $filter['st'];
				$ctr = 0;

				foreach ($st as $value)
				{
					$where .= $ctr > 0 ? ' or ':'';
					$where .= " p.product_name like '%{$value}%' ";
					$ctr = 1;

					$listfilter[] = $value.'|st|'.$value;
				}

				$where .= " ) ";
			}

			if(array_key_exists('sort', $filter))
			{
				if($ctr == 0) $where = '';

				$o = explode(' by ',$filter['sort'][0]);
				$col = $o[0] == 'Name' ? 'product_name':'created_at';
				$st = $o[1] == 'ascending' ? '':'desc';
				$order = " order by p.{$col} {$st}";
			}

			$qry = "select * from products p {$where} {$order}";

			return array(DB::select($qry),$listfilter);
		}
		
		return array(Product::orderBy('created_at','desc')->take(20)->get(),array());
	}

	public static function registryProd($id)
	{
		$qry = "
			select *
			from products p
				inner join `registry-product` rp
					on p.id = rp.prod_id
			where reg_id = '{$id}'
		";

		return DB::select($qry);
	}

}

app/views/admin/products/create-product.blade.php
@extends('admintemplate')

@section('content')

@if(Session::get('regadmin'))
<div class="nNote {{ Session::get('regadmin') }}">
    <p>{{ Session::get('addmsg') }}</p>
</div>
@endif

<div class="fluid">
    <div class="widget grid12">
        <div class="whead"><h6>Product Form</h6><div class="clear"></div></div>
        @foreach($errors->all('<p style="text-align: center">:message</p>') as $message)
            {{ $message }}
        @endforeach
        <div class="body">
        	<form method="post" action="{{ URL::route('admin.products.store') }}" id="frmnewproduct" enctype="multipart/form-data">
        		<div class="formRow">
                    <div class="grid3"><label>Product Name:</label></div>
                    <div class="grid9"><input type="text" name="product_name" value="{{ Input::old('product_name') }}" class="required"/></div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Short Description(thumbnail):</label></div>
                    <div class="grid9">
                        <textarea rows="8" class="auto lim" name="short_description">{{ Input::old('short_description') }}</textarea>
                        <span class="note" id="limitingtext">Field limited to 200 characters.</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Product Details:</label></div>
                    <div class="grid9" style="border: 1px solid #d7d7d7">
                        <textarea id="editor" name="product_details" rows="" cols="16" class="required">{{ Input::old('product_details') }}</textarea>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="formRow">
                    <div class="grid3"><label>Categories: </label></div>
                    <div class="grid9">
                        <select data-placeholder="Select category here" class="fullwidth select" multiple="multiple" tabindex="6" name="categories[]">
                            <option value=""></option>
                            @foreach($maincat as $mc)

                            <optgroup label="{{ $mc->occasion_type }}">
                                <?php $cats = Occasion::where('occasion_type','=',$mc->id)->get(); ?>
                                @foreach($cats as $cat)
                                <option value="{{ $cat->id }}">{{ $cat->occasion_name }}</option>
                                @endforeach
                            </optgroup>

                            @endforeach
                            
                        </select>  
                    </div>             
                    <div class="clear"></div>
                </div>

                <div class="formRow">
                    <div class="grid3"><label>Tags:</label></div>
                    <div class="grid9">
                        <input type="text" id="tags" name="tags" class="tags" value="" />
                        <span>*To multiple tags, press "ENTER" on every other tag that you indicate.</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Recipient:</label></div>
                    <div class="grid9 check">
                        @foreach($recipients as $row)

                        <input type="checkbox" checked="checked" name="recipient[]" value="{{ $row->recipient_id }}" />
                        <label for="check1"  class="mr20">{{ $row->recipient }}</label>

                        @endforeach
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Product Location:</label></div>
                    <div class="grid9 check">
                        @foreach($states as $row1)

                        <input type="checkbox" checked="checked" name="product_location[]" value="{{ $row1->state }}"/>
                        <label for="check1"  class="mr20">{{ $row1->state }}</label>
                        <div class="clear"></div>

                        @endforeach
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Price:</label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="price" value="{{ Input::old('price') }}" class="required"/></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Validity: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="validity" value="{{ Input::old('validity') }}" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Free exchange: </label></div>
                    <div class="grid9 on_off">
                        <div class="floatL mr10"><input type="checkbox" id="check20" checked="checked" name="free_exchange" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Delivery Date: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="delivery_date" value="{{ Input::old('delivery_date') }}" class="datepicker"/></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Delivery Cost: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="delivery_cost" value="{{ Input::old('delivery_cost') }}" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">    
                    <div class="grid3"><label>Upload image(s): </label></div>
                    <div class="grid9">
                        <div class="floatL mr10"><input type="file" name="imgs[]" multiple class="upl" /></div>
                        <span class="num-file"></span>
                    </div>
                    <div class="clear"></div>               
                </div>
                <div class="formRow">
                    <input type="submit" class="buttonL bGreen floatR" value="+ Product" />
                    <div class="clear"></div>
                </div>

        	</form>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('#frmnewproduct').validate();

    $('.upl').change(function(){
        var n = $("input:file")[0].files.length;
        $('.num-file').text(n+' file(s)');
    });
});
</script>

@endsection

@section('subnav')

    @include('admin.products.psubnav')

@endsection

app/views/admin/products/edit-product.blade.php
@extends('admintemplate')

@section('content')

@if(Session::get('regadmin'))
<div class="nNote {{ Session::get('regadmin') }}">
    <p>{{ Session::get('addmsg') }}</p>
</div>
@endif

<div class="fluid">
    <div class="widget grid12">
        <div class="whead"><h6>Product Form</h6><div class="clear"></div></div>
        @foreach($errors->all('<p style="text-align: center">:message</p>') as $message)
            {{ $message }}
        @endforeach
        <div class="body">
        	<!-- <form method="put" action="{{ URL::route('admin.products.update',$product->id) }}" id="frmnewproduct" enctype="multipart/form-data"> -->
            {{ Form::open(array('route' => array('admin.products.update',$product->id),'files'=>true,'method'=>'put')) }}
        		<div class="formRow">
                    <div class="grid3"><label>Product Name:</label></div>
                    <div class="grid9"><input type="text" name="product_name" value="{{ $product->product_name }}" class="required"/></div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Short Description(thumbnail):</label></div>
                    <div class="grid9">
                        <textarea rows="8" class="auto lim" name="short_description">{{ $product->short_description }}</textarea>
                        <span class="note" id="limitingtext">Field limited to 200 characters.</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Product Details:</label></div>
                    <div class="grid9" style="border: 1px solid #d7d7d7">
                        <textarea id="editor" name="product_details" rows="" cols="16" class="required">{{ $product->product_details }}</textarea>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="formRow">
                    <div class="grid3"><label>Categories:</label></div>
                    <div class="grid9">
                        <select data-placeholder="Select category here" class="fullwidth select required" multiple="multiple" tabindex="6" name="categories[]">
                            <option value=""></option>
                            @foreach($maincat as $mc)

                            <optgroup label="{{ $mc->occasion_type }}">
                                <?php $cats = Occasion::where('occasion_type','=',$mc->id)->get(); ?>
                                @foreach($cats as $cat)
                                <option value="{{ $cat->id }}" {{ in_array($cat->id,$product_occs) ? 'selected':'' }}>{{ $cat->occasion_name }}</option>
                                @endforeach
                            </optgroup>

                            @endforeach
                            
                        </select>  
                    </div>             
                    <div class="clear"></div>
                </div>

                <div class="formRow">
                    <div class="grid3"><label>Tags:</label></div>
                    <div class="grid9">
                        <input type="text" id="tags" name="tags" class="tags" value="{{ $product->tags }}" />
                        <span>*To multiple tags, press "ENTER" on every other tag that you indicate.</span>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Recipient:</label></div>
                    <div class="grid9 check">
                        @foreach($recipients as $row)

                        <input type="checkbox" {{ in_array($row->recipient_id,$product_recipient) ? 'checked':'' }} name="recipient[]" value="{{ $row->recipient_id }}" />
                        <label for="check1"  class="mr20">{{ $row->recipient }}</label>

                        @endforeach
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Product Location:</label></div>
                    <div class="grid9 check">
                        @foreach($states as $row1)

                        <input type="checkbox" {{ in_array($row1->state,$product_location) ? 'checked':'' }} name="product_location[]" value="{{ $row1->state }}"/>
                        <label for="check1"  class="mr20">{{ $row1->state }}</label>
                        <div class="clear"></div>

                        @endforeach
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Price:</label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="price" value="{{ $product->price }}" class="required" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Validity: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="validity" value="{{ $product->validity }}" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Free exchange: </label></div>
                    <div class="grid9 on_off">
                        <div class="floatL mr10"><input type="checkbox" id="check20" {{ $product->free_exchange ? 'checked':'' }} name="free_exchange" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Delivery Date: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="delivery_date" value="{{ date('m-d-Y',strtotime($product->delivery_date)) }}" class="datepicker"/></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">
                    <div class="grid3"><label>Delivery Cost: </label></div>
                    <div class="grid9 enabled_disabled">
                        <div class="floatL mr10"><input type="text" name="delivery_cost" value="{{ $product->delivery_cost }}" /></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <div class="formRow">    
                    <div class="grid3"><label>Upload image(s): </label></div>
                    <div class="grid9">
                        <div class="floatL mr10"><input type="file" name="imgs[]" multiple class="upl" /></div>
                        <span class="num-file"></span>
                    </div>
                    <div class="gallery">
                        @if(count($imgs) > 0)
                        <ul>
                            @foreach($imgs as $img)
                            <li style="height:80px;width: 93px;">
                                <a href="{{ URL::to('/') }}/uploads/products/{{ $img->image }}" title="" class="lightbox">
                                    <img src="{{ URL::to('/') }}/uploads/products/smallthumb_{{ $img->image }}" alt="" />
                                </a>
                                <span><a href="#" url="{{ $url }}?id={{ $img->pi_id }}&pid={{ $img->product_id }}" class="delssimg" style="display: inline-block">Delete</a></span> | <span><a href="" style="display: inline-block">Primary</a></span>
                            </li>
                            @endforeach
                        </ul>
                        @else
                        <p>No image uploaded</p>
                        @endif
                    </div>
                    <div class="clear"></div>               
                </div>
                <div class="formRow">
                    <a href="#" class="buttonM bRed ml10 floatR" id="modal_open">Delete this product</a>
                    <input type="submit" class="buttonL bGreen floatR" value="+ Update Product" />
                    <div class="clear"></div>
                </div>
        	</form>
        </div>
    </div>
</div>

{{ Form::open(array('route' => array('admin.products.destroy',$product->id),'method'=>'delete','id'=>'frmdestroyprod')) }}</form>

<div id="dialog-modal" title="Please confirm...">
    <p>Are you sure you want to delete this product?</p>
</div>

<script type="text/javascript">
$(document).ready(function() {
    $('#frmnewproduct').validate();

    $('.upl').change(function(){
        var n = $("input:file")[0].files.length;
        $('.num-file').text(n+' file(s)');
    });

    $('.delssimg').click(function(){
        var a = confirm("Are you sure you want to delete this image?");
        var url = $(this).attr('url');

        if(a)
            window.location.href = url;
    });
});
</script>

@endsection

@section('subnav')

    @include('admin.products.psubnav')

@endsection

app/views/admin/products/psubnav.blade.php
<li {{ Request::segment(2) == 'products' && Request::segment(3) == '' ? 'class="activeli"':'' }}>
	<a href="{{ URL::to('admin/products') }}" title="" {{ Request::segment(3) == 'products' && Request::segment(3) == '' ? 'class="this"':'' }}>
		<span class="icos-cog2"></span>
		Products
	</a>
</li>

<li {{ Request::segment(3) == 'create' ? 'class="activeli"':'' }}>
	<a href="{{ URL::to('admin/products/create') }}" title="" {{ Request::segment(3) == 'create' ? 'class="this"':'' }}>
		<span class="icos-cog2"></span>
		Add Product
	</a>
</li>

<li {{ Request::segment(2) == 'recipient' ? 'class="activeli"':'' }}>
	<a href="{{ URL::to('admin/recipient') }}" title="" {{ Request::segment(2) == 'recipient' ? 'class="this"':'' }}>
		<span class="icos-cog2"></span>
		Add Recipient
	</a>
</li>

<li {{ Request::segment(2) == 'gift-certs' ? 'class="activeli"':'' }}>
	<a href="{{ URL::to('admin/gift-certs') }}" title="" {{ Request::segment(2) == 'gift-certs' ? 'class="this"':'' }}>
		<span class="icos-cog2"></span>
		Gift Certificate
	</a>
</li>